Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: dm
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: artifact-4e82b449817b4947a234
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        ArchitectureDiagramUrl: 'docs/architecture.png'
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-nanjing
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - na-south-1
          - eu-west-1
          - me-east-1
          - me-central-1
          - eu-central-1
  ServiceType: private
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变配ECS实例规格
            Description: 变配ECS实例规格
            Type: Custom
            SupportPredefinedParameters: false
            EnableLogging: false
            Parameters:
              - EcsInstanceType
  UpgradeMetadata:
    Description: 升级
    SupportRollback: true
    SupportUpgradeFromVersions: [ ]
    UpgradeComponents:
      - Configuration
      - Resource
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: spring boot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot单机版(软件包)
  ShareType: Public
  ApprovalType: Manual
